# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Roy Hritaban
email: h.roy.23@abdn.ac.uk
name: Roy H.
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrbz
github_username:  asdfasdfasdf

# Build settings
#theme: minima
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed

author:
  name: "Hritaban Roy"
  avatar: "/assets/headshot_square.jpeg"
  bio: "Computing Science fresher at the University of Aberdeen. Skilled in Python and Data Analytics. Currently learning AI and web development. Eager to collaborate and contribute to the tech community." # Note: Markdown is allowed
  location: "Aberdeen, Scotland"
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/hritabanroy/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/royhritaban"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/hritabanr/"

defaults:
  #_posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
include: ["_pages"]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

